/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthRouteImport } from "./routes/_auth";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthVerifyRouteImport } from "./routes/_auth/verify";
import { Route as AuthResetPasswordRouteImport } from "./routes/_auth/reset-password";
import { Route as AuthRegisterRouteImport } from "./routes/_auth/register";
import { Route as AuthLoginRouteImport } from "./routes/_auth/login";
import { Route as AuthKycRouteImport } from "./routes/_auth/kyc";
import { Route as AuthForgotPasswordRouteImport } from "./routes/_auth/forgot-password";

const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: "/verify",
  path: "/verify",
  getParentRoute: () => AuthRoute,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => AuthRoute,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any);
const AuthKycRoute = AuthKycRouteImport.update({
  id: "/kyc",
  path: "/kyc",
  getParentRoute: () => AuthRoute,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/forgot-password": typeof AuthForgotPasswordRoute;
  "/kyc": typeof AuthKycRoute;
  "/login": typeof AuthLoginRoute;
  "/register": typeof AuthRegisterRoute;
  "/reset-password": typeof AuthResetPasswordRoute;
  "/verify": typeof AuthVerifyRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/forgot-password": typeof AuthForgotPasswordRoute;
  "/kyc": typeof AuthKycRoute;
  "/login": typeof AuthLoginRoute;
  "/register": typeof AuthRegisterRoute;
  "/reset-password": typeof AuthResetPasswordRoute;
  "/verify": typeof AuthVerifyRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRouteWithChildren;
  "/_auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/_auth/kyc": typeof AuthKycRoute;
  "/_auth/login": typeof AuthLoginRoute;
  "/_auth/register": typeof AuthRegisterRoute;
  "/_auth/reset-password": typeof AuthResetPasswordRoute;
  "/_auth/verify": typeof AuthVerifyRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/forgot-password"
    | "/kyc"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/verify";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/forgot-password"
    | "/kyc"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/verify";
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/_auth/forgot-password"
    | "/_auth/kyc"
    | "/_auth/login"
    | "/_auth/register"
    | "/_auth/reset-password"
    | "/_auth/verify";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/verify": {
      id: "/_auth/verify";
      path: "/verify";
      fullPath: "/verify";
      preLoaderRoute: typeof AuthVerifyRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/reset-password": {
      id: "/_auth/reset-password";
      path: "/reset-password";
      fullPath: "/reset-password";
      preLoaderRoute: typeof AuthResetPasswordRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/register": {
      id: "/_auth/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof AuthRegisterRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/login": {
      id: "/_auth/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/kyc": {
      id: "/_auth/kyc";
      path: "/kyc";
      fullPath: "/kyc";
      preLoaderRoute: typeof AuthKycRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/forgot-password": {
      id: "/_auth/forgot-password";
      path: "/forgot-password";
      fullPath: "/forgot-password";
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof AuthRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthKycRoute: typeof AuthKycRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
  AuthVerifyRoute: typeof AuthVerifyRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthKycRoute: AuthKycRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
